define('gettext', ['jed'], function () {

    'use strict';

    var i18n = new Jed({

        // You can choose to set the domain at instantiation time
        // If you don't, then "messages" will be used by default
        //"domain" : "the_domain",

        // This callback is called when a key is missing
        "missing_key_callback" : function(key) {
            // Do something with the missing key
            // e.g. send key to web service or
            console.error(key)
        },

        // This is the translation data, which is often generated by
        // a po2json converter. You would ideally have one per locale
        // and only pull in the locale_data that you need.
        "locale_data" : {
            "messages": {
                "": {
                    "domain": "messages",
                    "lang": "de",
                    "plural_forms" : "nplurals=2; plural=(n != 1);"
                },
                "Link to this marker": ['Link zu dieser Markierung'],
            }
        }
    });

    function gt(id) {
        var out=i18n.translate(id).fetch();
        console.log(id,out);
        return out;
    }
    gt.load = function (name, req, onload, config) {
        var userLang = navigator.language || navigator.userLanguage; 
        console.log('gt.load',name, req);
        onload(gt);

    };
    return gt;
});
